# # # # # # # # # # #
#  自动构建 PSG1218
#      
# # # # # # # # # # #
name: Padavan CI PSG1218
on: 
  release:
    types: [published]

  push:
    branches: 
      - master

  schedule:
    - cron: 0 19 * * *
  
  watch:
    types: [started]
env:
  UPLOAD_COWTRANSFER: true
  UPLOAD_WETRANSFER: true
jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id  # 自己点的 start
    steps:
    - name: Checkout Master            # 1.导入主分支
      uses: actions/checkout@master
    - name: Build Padavan 
      env:
        DEBIAN_FRONTEND: noninteractive  # 非交互模式
      run: |
           apt-get update \
           && apt-get install -qy apt-utils 
- name: Upload firmware to cowtransfer
      if: env.UPLOAD_COWTRANSFER == 'true' && success()
      run: |
        curl -fsSL git.io/file-transfer | sh
        ./transfer cow --block 2621440 -s -p 64 --no-progress ${IMAGES_PATH} 2>&1 | tee cowtransfer.log
        echo "::warning file=cowtransfer.com::$(cat cowtransfer.log | grep https)"
    - name: Upload firmware to WeTransfer
      if: env.UPLOAD_WETRANSFER == 'true' && success()
      run: |
        curl -fsSL git.io/file-transfer | sh
        ./transfer wet -s -p 16 --no-progress ${IMAGES_PATH} 2>&1 | tee wetransfer.log
        echo "::warning file=wetransfer.com::$(cat wetransfer.log | grep https)"
