# # # # # # # # # # #
#  自动构建 PSG1218
#      
# # # # # # # # # # #
name: Padavan CI PSG1218
on: 
  release:
    types: [published]

  push:
    branches: 
      - master

  schedule:
    - cron: 0 19 * * *
  
  watch:
    types: [started]
env:
  UPLOAD_COWTRANSFER: true
  UPLOAD_WETRANSFER: true
jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id  # 自己点的 start
    steps:
    - name: Build Padavan 
      env:
        DEBIAN_FRONTEND: noninteractive  # 非交互模式
      run: |
               apt-get update 
	       apt-get install -qy apt-utils 
	       apt-get -qy install locales locale-gen --no-purge en_US.UTF-8 
	       apt-get install -qy \
	       git \
	       build-essential \
	       gawk \
	       pkg-config \
	       gettext \
	       automake \
	       autoconf \
	       autopoint \
	       libtool \
	       bison \
	       flex \
	       zlib1g-dev \
	       libgmp3-dev \
	       libmpfr-dev \
	       libmpc-dev \
	       texinfo \
	       mc \
	       libncurses5-dev \
	       nano \
	       vim \
  	       autopoint \
	       gperf \
	       python-docutils \
	       module-init-tools \
	        git clone https://bitbucket.org/padavan/rt-n56u.git /opt/rt-n56u 
	        sed -i 's/sudo//g' /opt/rt-n56u/trunk/tools/depmod.sh 
	        sed -i 's/sudo//g' /opt/rt-n56u/trunk/user/scripts/makedevlinks 
	        sed -i 's/sudo//g' /opt/rt-n56u/trunk/vendors/Ralink/MT7620/Makefile 
                cp config/ac54u_base.config /opt/rt-n56u/trunk/.config 
	        cp config/board.h /opt/rt-n56u/trunk/configs/boards/RT-AC54U/board.h 
	        cp config/kernel-3.4.x.config /opt/rt-n56u/trunk/configs/boards/RT-AC54U/kernel-3.4.x.config 
	        cp config/board.mk /opt/rt-n56u/trunk/configs/boards/RT-AC54U/board.mk 
	        cp config/defaults.h /opt/rt-n56u/trunk/user/shared/defaults.h 
	        cp config/CN.dict /opt/rt-n56u/trunk/user/www/dict/ 
	        cp config/Makefile /opt/rt-n56u/trunk/user/www/ 
	        cp Stock_v21.4.6.10/MT7612E_EEPROM.bin /opt/rt-n56u/trunk/vendors/Ralink/MT7620/MT7612E_EEPROM.bin 
	        cp Stock_v21.4.6.10/MT7620_AP_2T2R-4L_V15.BIN /opt/rt-n56u/trunk/vendors/Ralink/MT7620/MT7620_AP_2T2R-4L_external_LNA_external_PA_V15.bin 
	        cd /opt/rt-n56u/toolchain-mipsel 
	        ./clean_sources 
	        ./build_toolchain_3.4.x 
	        cd /opt/rt-n56u/trunk 
	        ./clear_tree 
	        ./build_firmware 
	        mkdir -p /root/images 
	        cp /opt/rt-n56u/trunk/images/*.trx /opt/rt-n56u/images
    echo "::set-env name=FILE_NAME::PSG1218-$(date "+%Y%m%d")"  # 包名
        echo "::set-env name=IMAGES_PATH::/opt/rt-n56u/images/"      # 打包目录
        echo "::set-output name=status::success"    
        
    - name: Upload firmware to cowtransfer
      if: env.UPLOAD_COWTRANSFER == 'true' && success()
      run: |
        curl -fsSL git.io/file-transfer | sh
        ./transfer cow --block 2621440 -s -p 64 --no-progress ${IMAGES_PATH} 2>&1 | tee cowtransfer.log
        echo "::warning file=cowtransfer.com::$(cat cowtransfer.log | grep https)"
    - name: Upload firmware to WeTransfer
      if: env.UPLOAD_WETRANSFER == 'true' && success()
      run: |
        curl -fsSL git.io/file-transfer | sh
        ./transfer wet -s -p 16 --no-progress ${IMAGES_PATH} 2>&1 | tee wetransfer.log
        echo "::warning file=wetransfer.com::$(cat wetransfer.log | grep https)"
